# Kubernetes v1.27+
# Development environment secrets configuration with FedRAMP High and CJIS compliance

apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: crimeminer-backend
  labels:
    app: auth-service
    environment: development
    compliance-level: fedramp-high
    data-classification: sensitive-law-enforcement
    encryption: aes-256-gcm
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "auth-service"
    audit.k8s.io/level: "detailed"
    security.cloud.google.com/cis-benchmark: "true"
type: Opaque
data:
  JWT_SECRET: ${JWT_SECRET}
  KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
  MFA_SECRET_KEY: ${MFA_SECRET_KEY}
  SESSION_ENCRYPTION_KEY: ${SESSION_ENCRYPTION_KEY}
  TOKEN_SIGNING_KEY: ${TOKEN_SIGNING_KEY}

---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: crimeminer-backend
  labels:
    environment: development
    compliance-level: fedramp-high
    data-classification: sensitive-law-enforcement
    encryption: aes-256-gcm
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "db-access"
    audit.k8s.io/level: "detailed"
type: Opaque
data:
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
  DB_SSL_CERT: ${DB_SSL_CERT}
  DB_ENCRYPTION_KEY: ${DB_ENCRYPTION_KEY}

---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: crimeminer-backend
  labels:
    environment: development
    compliance-level: fedramp-high
    data-classification: sensitive-law-enforcement
    cloud-provider: aws
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "aws-access"
    iam.amazonaws.com/role: "development-role"
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_REGION: ${AWS_REGION}
  AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
  AWS_KMS_KEY_ID: ${AWS_KMS_KEY_ID}

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-certificates
  namespace: crimeminer-backend
  labels:
    environment: development
    compliance-level: fedramp-high
    data-classification: sensitive-law-enforcement
    encryption: fips-140-2
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
    cert-manager.io/common-name: "*.crimeminer.dev"
    cert-manager.io/key-algorithm: "RSA-4096"
type: kubernetes.io/tls
data:
  tls.crt: ${TLS_CERTIFICATE}
  tls.key: ${TLS_PRIVATE_KEY}
  ca.crt: ${CA_CERTIFICATE}