# Production environment secrets configuration for CrimeMiner platform
# Implements FedRAMP High and CJIS compliant secret management with HashiCorp Vault v3.23.0
# Requires: Kubernetes v1.27+, TLS v1.3+

---
# Database credentials with 24-hour rotation
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: crimeminer-backend
  labels:
    environment: production
    managed-by: vault
    rotation-period: 24h
    compliance: fedramp-high
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "database-credentials"
    vault.hashicorp.com/agent-pre-populate-only: "true"
    vault.hashicorp.com/agent-inject-status: "update"
    vault.hashicorp.com/secret-volume-path: "/vault/secrets"
    vault.hashicorp.com/log-level: "debug"
    audit.vault.hashicorp.com/enabled: "true"
type: Opaque

---
# AWS service credentials with weekly rotation
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: crimeminer-backend
  labels:
    environment: production
    managed-by: vault
    rotation-period: 168h
    compliance: fedramp-high
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "aws-credentials"
    vault.hashicorp.com/agent-pre-populate-only: "true"
    vault.hashicorp.com/agent-inject-status: "update"
    vault.hashicorp.com/secret-volume-path: "/vault/secrets"
    vault.hashicorp.com/log-level: "debug"
    audit.vault.hashicorp.com/enabled: "true"
type: Opaque

---
# JWT signing keys with monthly rotation
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: crimeminer-backend
  labels:
    environment: production
    managed-by: vault
    rotation-period: 720h
    compliance: fedramp-high
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "jwt-signing"
    vault.hashicorp.com/agent-pre-populate-only: "true"
    vault.hashicorp.com/agent-inject-status: "update"
    vault.hashicorp.com/secret-volume-path: "/vault/secrets"
    vault.hashicorp.com/log-level: "debug"
    audit.vault.hashicorp.com/enabled: "true"
type: Opaque

---
# TLS certificates with annual rotation
apiVersion: v1
kind: Secret
metadata:
  name: tls-certificates
  namespace: crimeminer-backend
  labels:
    environment: production
    managed-by: cert-manager
    rotation-period: 8760h
    compliance: fedramp-high
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
    cert-manager.io/common-name: "*.crimeminer.gov"
    cert-manager.io/duration: "8760h"
    cert-manager.io/renew-before: "720h"
    cert-manager.io/min-tls-version: "1.3"
    audit.cert-manager.io/enabled: "true"
type: kubernetes.io/tls