# Kubernetes v1.27+ Staging Environment Secrets Configuration
# HashiCorp Vault v3.23.0 Integration
# FedRAMP High and CJIS Compliant Secret Management

---
# Database credentials with 24h rotation
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: crimeminer-backend
  labels:
    environment: staging
    managed-by: vault
    fedramp-level: high
    cjis-compliant: "true"
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "database-credentials-staging"
    vault.hashicorp.com/agent-pre-populate-only: "true"
    vault.hashicorp.com/secret-rotation: "24h"
    vault.hashicorp.com/audit-log-enabled: "true"
type: Opaque

---
# AWS service credentials with 7-day rotation
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: crimeminer-backend
  labels:
    environment: staging
    managed-by: vault
    fedramp-level: high
    cjis-compliant: "true"
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "aws-credentials-staging"
    vault.hashicorp.com/agent-pre-populate-only: "true"
    vault.hashicorp.com/secret-rotation: "168h"
    vault.hashicorp.com/audit-log-enabled: "true"
type: Opaque

---
# JWT signing keys with 30-day rotation
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: crimeminer-backend
  labels:
    environment: staging
    managed-by: vault
    fedramp-level: high
    cjis-compliant: "true"
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "jwt-signing-staging"
    vault.hashicorp.com/agent-pre-populate-only: "true"
    vault.hashicorp.com/secret-rotation: "720h"
    vault.hashicorp.com/audit-log-enabled: "true"
type: Opaque

---
# TLS certificates with 1-year validity
apiVersion: v1
kind: Secret
metadata:
  name: tls-certificates
  namespace: crimeminer-backend
  labels:
    environment: staging
    managed-by: cert-manager
    fedramp-level: high
    cjis-compliant: "true"
  annotations:
    cert-manager.io/issuer: "letsencrypt-staging"
    cert-manager.io/common-name: "*.staging.crimeminer.gov"
    cert-manager.io/duration: "8760h"
    cert-manager.io/renew-before: "720h"
    cert-manager.io/min-tls-version: "TLSv1.3"
    vault.hashicorp.com/audit-log-enabled: "true"
type: kubernetes.io/tls