# Loki Server Configuration v2.8.0
# Implements FedRAMP High and CJIS compliant logging with 7-year retention

auth_enabled: true

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  grpc_server_max_recv_msg_size: 67108864  # 64MB
  grpc_server_max_send_msg_size: 67108864  # 64MB
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s
  http_server_idle_timeout: 120s

auth_config:
  type: jwt
  secret_key: ${JWT_SECRET}
  ttl: 12h
  max_inactive_period: 1h
  enable_tls: true
  tls_min_version: TLS1.2

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 3
      heartbeat_timeout: 1m
  chunk_idle_period: 1h
  max_chunk_age: 2h
  chunk_target_size: 1048576  # 1MB
  chunk_retain_period: 30s
  max_transfer_retries: 3
  wal:
    enabled: true
    dir: /data/loki/wal
    replay_memory_ceiling: 512MB

schema_config:
  configs:
    - from: "2023-01-01"
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /data/loki/index
    cache_location: /data/loki/cache
    cache_ttl: 24h
    shared_store: s3
    resync_interval: 5m
  aws:
    s3:
      region: ${AWS_REGION}
      bucket_name: ${LOGS_BUCKET_NAME}
      sse_encryption: true
      sse_type: aws:kms
      kms_key_id: ${KMS_KEY_ID}
      insecure: false
      force_path_style: false
      http_config:
        idle_conn_timeout: 90s
        response_header_timeout: 30s
        insecure_skip_verify: false
      s3forcepathstyle: false

limits_config:
  retention_period: 7y  # FedRAMP/CJIS compliance requirement
  enforce_metric_name: false
  max_entries_limit_per_query: 10000
  max_query_series: 5000
  max_query_lookback: 2160h  # 90 days
  per_tenant_rate_limit: 100000
  max_global_streams_per_user: 10000
  ingestion_rate_mb: 100
  ingestion_burst_size_mb: 200
  max_chunk_age: 2h

compactor:
  working_directory: /data/loki/compactor
  shared_store: s3
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  delete_request_cancel_period: 24h

ruler:
  storage:
    type: s3
    s3:
      bucket_name: ${RULER_BUCKET_NAME}
      sse_encryption: true
      sse_type: aws:kms
      kms_key_id: ${KMS_KEY_ID}
  rule_path: /data/loki/rules
  alertmanager_url: http://alertmanager.crimeminer-system:9093
  ring:
    kvstore:
      store: memberlist
  enable_api: true
  enable_alertmanager_v2: true
  evaluation_interval: 1m
  poll_interval: 1m
  concurrent_executions: 10

memberlist:
  join_members:
    - loki-memberlist
  dead_node_reclaim_time: 30s
  gossip_interval: 5s
  gossip_nodes: 3
  retransmit_factor: 2
  packet_dial_timeout: 5s
  packet_write_timeout: 5s

tracing:
  enabled: true
  type: jaeger
  jaeger:
    sampler_type: ratelimiting
    sampler_param: 10

analytics:
  reporting_enabled: false